import AppProvider from '@/components/AppContext'
import Header from '@/components/layout/Header'
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { SessionProvider } from 'next-auth/react';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-6xl mx-auto p-2 md:p-5">
          <AppProvider>
          <Header/>
          {children}
          <footer className="border-t p-8 text-center text-gray-500 mt-8">
            &copy; 2024 all rights reserved
          </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
